### ISSUE TITLE
Highlighters config not included into the YAML export

### ISSUE THREAD

**Issue by righettod** [silentsignal/burp-piper#21]
Hi,

I have configured a highlighter script that is functional and enabled but when I export the configuration as YAML it is not taken into account:

![image](https://user-images.githubusercontent.com/1573775/100330881-c97bc680-2fcf-11eb-8422-2bc9cafad9ab.png)

![image](https://user-images.githubusercontent.com/1573775/100331025-f5974780-2fcf-11eb-8b41-c21eddc6ccc1.png)

It is me that had missed something?

Thank you very much in advance for your feedback.

**Comment by dnet** [comment]
Thanks, nice catch, I released [v0.7.1](https://github.com/silentsignal/burp-piper/releases/tag/v0.7.1) that contains the fix. BApp Store will probably also have it in a few days.

**Comment by righettod** [comment]
Thank a lot for the fix and this amazing extension 👍
